name: purity_stopwatch_example
version: 0.0.0
author: "Daniel Robinson\r\n<daniel.robinson.dart@gmail.com>"
description: A sample Purity web application
homepage: http://github.com/0xor1/purity_stopwatch_example
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  browser: any
  purity: '>=0.9.0 <0.10.0'
  polymer: '>=0.14.0 <0.15.0'
  core_elements: ">=0.2.0 <0.3.0"
  paper_elements: ">=0.2.0 <0.3.0"
transformers:
- polymer:
    entry_points: web/index.html , index_without_purity.html , index_with_purity.html

